--un client peut signe 0 à N contrat
--un contrat peut-être signé par un et un seul client
--Un client possède 0 à N véhicule
--Un véhicule appartient à 1 et 1 seul véhicule
--Un contrat couvre aucun ou un véhicule
--Un véhicule est couvert par un et un seul contrat
--Un accident implique 0 à N véhicule
--Un véhicule peut-être impliqué dans 0 à N accident
--Insertion :
--Ajouter aussi des choses qui ne marcheront pas afin d'être sûre que notre modèle ne les permettent pas


--insertion des clients
INSERT INTO CLIENT(NUMCLIENT,NOM,ADRESSE,LOCALITE)
--client qui possède une voiture et le contrat associé à celle-ci, elle a été impliqué dans un accident
values ((SELECT COUNT(NUMCLIENT)+1 FROM CLIENT),"DUJARDIN","1,rue de la Chapelle","Strasbourg");

INSERT INTO CLIENT(NUMCLIENT,NOM,ADRESSE,LOCALITE)
--client qui possède une voiture et le contrat associé, elle a été impliqué dans deux accidents dont un qui a eu lieu avant qu'elle soit assurée
values ((SELECT COUNT(NUMCLIENT)+1 FROM CLIENT),"MURE","1, rue de la gauche","Strasbourg");

INSERT INTO CLIENT(NUMCLIENT,NOM,ADRESSE,LOCALITE)
-- client qui possède un contrat mais aucune voiture associé, il n'est donc pas impliqué dans un accident
values ((SELECT COUNT(NUMCLIENT)+1 FROM CLIENT),"KLEINCLAUS","20, rue de la bonne note","Vendenheim");

INSERT INTO CLIENT(NUMCLIENT,NOM,ADRESSE,LOCALITE)
--client qui ne possède deux voitures toutes les deux assurrées, qui sont impliqués dans le même accident
values ((SELECT COUNT(NUMCLIENT)+1 FROM CLIENT),"FOUBERT","2, rue de Strasbourg","Strasbourg");

INSERT INTO CLIENT(NUMCLIENT,NOM,ADRESSE,LOCALITE)
--client qui ne possède ni contrat ni voiture
values ((SELECT COUNT(NUMCLIENT)+1 FROM CLIENT),"HATTON","9, avenue de la forêt noire","Strasbourg");

INSERT INTO CLIENT(NUMCLIENT,NOM,ADRESSE,LOCALITE)
--client qui possède une voiture mais pas de contrat
values ((SELECT COUNT(NUMCLIENT)+1 FROM CLIENT),"BENIGNI","9,rue de la ziegelau", "Strasbourg");

INSERT INTO CLIENT(NUMCLIENT,NOM,ADRESSE,LOCALITE)
--client qui possède une voiture, un contrat et est impliqué dans aucun accident
values ((SELECT COUNT(NUMCLIENT)+1 FROM CLIENT),"CORRECTION","0,rue de la faute", "Strasbourg");

--insertion des accidents
INSERT INTO ACCIDENT(NUMACC,DATEACC,MONTANT)
--accident qui implique la voiture de dujardin (montant nul (pas responsable?))
values ((SELECT COUNT(NUMACC)+1 FROM ACCIDENT),'2017-06-01',null);

INSERT INTO ACCIDENT(NUMACC,DATEACC,MONTANT)
--accident qui n'implique aucunes voiture enregistrées dans la base
values ((SELECT COUNT(NUMACC)+1 FROM ACCIDENT),'2017-05-02',1000);

INSERT INTO ACCIDENT(NUMACC,DATEACC,MONTANT)
--accident qui implique la voiture de Mure qui été assurée
values ((SELECT COUNT(NUMACC)+1 FROM ACCIDENT),'2017-04-30',10);

INSERT INTO ACCIDENT(NUMACC,DATEACC,MONTANT)
--accident qui implique la voiture de Mure avant qu'elle ne soit assurée (montant nul pas assuré ?)
values ((SELECT COUNT(NUMACC)+1 FROM ACCIDENT),'2017-03-10',null);

INSERT INTO ACCIDENT(NUMACC,DATEACC,MONTANT)
--accident qui implique les voiture de Foubert
values ((SELECT COUNT(NUMACC)+1 FROM ACCIDENT),'2017-02-13',500000);

--insertion des contrats
INSERT INTO CONTRAT(SIGNATAIRE,NUMCTR,TYPE,DATESIGN)
--contrat de correction
values ((SELECT NUMCLIENT FROM CLIENT WHERE NOM="CORRECTION"),(SELECT COUNT(NUMCTR)+1 FROM CONTRAT),"TIERS",'2017-01-01');

INSERT INTO CONTRAT(SIGNATAIRE,NUMCTR,TYPE,DATESIGN)
--contrat de la voiture de dujardin
values ((SELECT NUMCLIENT FROM CLIENT WHERE NOM="DUJARDIN"),(SELECT COUNT(NUMCTR)+1 FROM CONTRAT),"TIERS",'2017-01-01');

INSERT INTO CONTRAT(SIGNATAIRE,NUMCTR,TYPE,DATESIGN)
--contrat de la première voiture de Foubert
values ((SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT"),(SELECT COUNT(NUMCTR)+1 FROM CONTRAT),"TOUT RISQUE",'2017-01-01');

INSERT INTO CONTRAT(SIGNATAIRE,NUMCTR,TYPE,DATESIGN)
--contrat de sa deuxième voiture de Foubert
values ((SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT"),(SELECT COUNT(NUMCTR)+1 FROM CONTRAT),"TOUT RISQUE",'2017-01-02');

INSERT INTO CONTRAT(SIGNATAIRE,NUMCTR,TYPE,DATESIGN)
--contrat de la voiture de Mure
values ((SELECT NUMCLIENT FROM CLIENT WHERE NOM="MURE"),(SELECT COUNT(NUMCTR)+1 FROM CONTRAT),"TOUT RISQUE",'2017-04-01');

INSERT INTO CONTRAT(SIGNATAIRE,NUMCTR,TYPE,DATESIGN)
--contrat de Kleinclaus mais lié à aucune voiture
values ((SELECT NUMCLIENT FROM CLIENT WHERE NOM="KLEINCLAUS"),(SELECT COUNT(NUMCTR)+1 FROM CONTRAT),"TOUT RISQUE",'2017-01-01');

--insertion des véhicules
INSERT INTO VEHICULE(NUMVEH,MARQUE,MODELE,ANNEE,CYLINDREE,SIGNATAIRE,NUMCTR,NUMCLIENT)
--voiture de correction
values ((SELECT COUNT(NUMVEH)+1 FROM VEHICULE ),"CITRÖEN","XSARA",1999,"1997 cc",(SELECT NUMCLIENT FROM CLIENT WHERE NOM="CORRECTION"),
	(SELECT NUMCTR FROM CONTRAT WHERE SIGNATAIRE=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="CORRECTION")),(SELECT NUMCLIENT FROM CLIENT WHERE NOM="CORRECTION"));

INSERT INTO VEHICULE(NUMVEH,MARQUE,MODELE,ANNEE,CYLINDREE,SIGNATAIRE,NUMCTR,NUMCLIENT)
--voiture de dujardin sous contrat
values ((SELECT COUNT(NUMVEH)+1 FROM VEHICULE ),"CITRÖEN","XSARA",1999,"1997 cc",(SELECT NUMCLIENT FROM CLIENT WHERE NOM="DUJARDIN"),(SELECT NUMCTR FROM CONTRAT WHERE SIGNATAIRE=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="DUJARDIN")),(SELECT NUMCLIENT FROM CLIENT WHERE NOM="DUJARDIN"));

INSERT INTO VEHICULE(NUMVEH,MARQUE,MODELE,ANNEE,CYLINDREE,SIGNATAIRE,NUMCTR,NUMCLIENT)
--première voiture de Foubert sous contrat
values ((SELECT COUNT(NUMVEH)+1 FROM VEHICULE ),"LAMBORGHINI","AVENTADOR",2016,"6498 cc",(SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT"),
	(SELECT NUMCTR FROM CONTRAT WHERE SIGNATAIRE=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT")),(SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT"));

INSERT INTO VEHICULE(NUMVEH,MARQUE,MODELE,ANNEE,CYLINDREE,SIGNATAIRE,NUMCTR,NUMCLIENT)
--deuxième voiture de Foubert sous contrat
values ((SELECT COUNT(NUMVEH)+1 FROM VEHICULE ),"FIAT","PUNTO",2002,"3000 cc",(SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT"),
	(SELECT NUMCTR FROM CONTRAT WHERE SIGNATAIRE=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT")),(SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT"));

INSERT INTO VEHICULE(NUMVEH,MARQUE,MODELE,ANNEE,CYLINDREE,SIGNATAIRE,NUMCTR,NUMCLIENT)
--voiture de Mure sous contrat
values ((SELECT COUNT(NUMVEH)+1 FROM VEHICULE ),"RENAULT","TWINGO",2007,"1500 cc",(SELECT NUMCLIENT FROM CLIENT WHERE NOM="MURE"),
	(SELECT NUMCTR FROM CONTRAT WHERE SIGNATAIRE=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="MURE")),(SELECT NUMCLIENT FROM CLIENT WHERE NOM="MURE"));

/*INSERT INTO VEHICULE(NUMVEH,MARQUE,MODELE,ANNEE,CYLINDREE,SIGNATAIRE,NUMCTR,NUMCLIENT)
--voiture de Benigni sans contrat
values ((SELECT COUNT(NUMVEH)+1 FROM VEHICULE ),"FERRARI","F12",2015,"5000 cc",(SELECT NUMCLIENT FROM CLIENT WHERE NOM="BENIGNI"),
	(SELECT NUMCTR FROM CONTRAT WHERE SIGNATAIRE=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="BENIGNI")),(SELECT NUMCLIENT FROM CLIENT WHERE NOM="BENIGNI"));*/
	--MARCHE PAS SANS CONTRAT

--insertion des implications
INSERT INTO IMPLICATION(NUMACC,NUMVEH)
--implication de la voiture de dujardin dans un accident
values ((SELECT NUMACC FROM ACCIDENT WHERE DATEACC='2017-06-01'),(SELECT NUMVEH FROM VEHICULE WHERE NUMCLIENT=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="DUJARDIN")));

INSERT INTO IMPLICATION(NUMACC,NUMVEH)
--Implications des voitures de Foubert dans le même accident
values ((SELECT NUMACC FROM ACCIDENT WHERE DATEACC='2017-02-13'),(SELECT MIN(NUMVEH) FROM VEHICULE WHERE NUMCLIENT=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT")));

INSERT INTO IMPLICATION(NUMACC,NUMVEH)
values ((SELECT NUMACC FROM ACCIDENT WHERE DATEACC='2017-02-13'),(SELECT MAX(NUMVEH) FROM VEHICULE WHERE NUMCLIENT=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="FOUBERT")));

INSERT INTO IMPLICATION(NUMACC,NUMVEH)
--Première implication de la voiture de Mure dans un accident (pas encore sous contrat)
values ((SELECT NUMACC FROM ACCIDENT WHERE DATEACC='2017-03-10'),(SELECT NUMVEH FROM VEHICULE WHERE NUMCLIENT=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="MURE")));

INSERT INTO IMPLICATION(NUMACC,NUMVEH)
--Deuxième implication de la voiture de Mure dans un accident (sous contrat)
values ((SELECT NUMACC FROM ACCIDENT WHERE DATEACC='2017-04-30'),(SELECT NUMVEH FROM VEHICULE WHERE NUMCLIENT=(SELECT NUMCLIENT FROM CLIENT WHERE NOM="MURE")));