--suppression données tables
DELETE FROM IMPLICATION;
DELETE FROM VEHICULE;
DELETE FROM CONTRAT;
DELETE FROM ACCIDENT;
DELETE FROM CLIENT;

--suppression des index
ALTER TABLE IMPLICATION
DROP INDEX XIMPLICATION_NUMACC_NUMVEH;

ALTER TABLE VEHICULE
DROP INDEX XVEHICULE_NUMVEH;

ALTER TABLE CONTRAT
DROP INDEX XCONTRAT_SIGNATAIRE_NUMCTR;

ALTER TABLE ACCIDENT
DROP INDEX XACCIDENT_NUMACC;

ALTER TABLE CLIENT
DROP INDEX XCLIENT_NUMCLIENT;

--suppression des foreign keys
ALTER TABLE IMPLICATION
DROP CONSTRAINT FK_IMPLICATION_ACCIDENT;

ALTER TABLE IMPLICATION
DROP CONSTRAINT FK_IMPLCATION_VEHICULE;

ALTER TABLE VEHICULE
DROP CONSTRAINT FK_VEHICULE_CLIENT;

ALTER TABLE VEHICULE
DROP CONSTRAINT FK_VEHICULE_CONTRAT;

ALTER TABLE CONTRAT
DROP CONSTRAINT FK_CONTRAT_CLIENT;

--suppression des primary keys
ALTER TABLE IMPLICATION
DROP CONSTRAINT PK_IMPLICATION;

ALTER TABLE VEHICULE
DROP CONSTRAINT PK_VEHICULE;

ALTER TABLE CONTRAT
DROP CONSTRAINT PK_CONTRAT;

ALTER TABLE ACCIDENT
DROP CONSTRAINT PK_ACCIDENT;

ALTER TABLE CLIENT
DROP CONSTRAINT PK_CLIENT;

--suppression des tables
DROP TABLE IMPLICATION;
DROP TABLE VEHICULE;
DROP TABLE CONTRAT;
DROP TABLE ACCIDENT;
DROP TABLE CLIENT;